name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gen-lang-client-0072471951 # Unified project ID
  SERVICE_NAME: easytools
  REGION: us-west1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_BACKEND_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          source: '.'
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
